### PR TITLE
Fix #378 by making culiteral_pow generic

### LINKED ISSUE #378: `CuArrays.culiteral_pow()` function breaks Flux
**Description**
Recent update of CuArrays breaks Flux due to the definition `CuArrays.culiteral_pow()` function.

**To Reproduce**
The Minimal Working Example (MWE) for this bug:
```julia
using CuArrays
using Flux

# using ForwardDiff
# CuArrays.culiteral_pow(::typeof(^), x::ForwardDiff.Dual{Nothing,Float32,1}, ::Val{2}) = x*x

X = rand(1,100) |> gpu
Y = rand(1,100) |> gpu

m = Chain(
    Dense(1, 1)
) |> gpu

loss(x, y) = Flux.mse(m(x), y)
Flux.train!(loss, params(m), [(X,Y)], ADAM())
```
The error is:
```
ERROR: LoadError: MethodError: no method matching culiteral_pow(::typeof(^), ::ForwardDiff.Dual{Nothing,Float32,1}, ::Val{2})
Closest candidates are:
  culiteral_pow(::typeof(^), !Matched::Union{Float32, Float64}, ::Val{2}) at /home/gawron/.julia/packages/CuArrays/eFBar/src/broadcast.jl:46
  culiteral_pow(::typeof(^), !Matched::Union{Float32, Float64}, ::Val{p}) where p at /home/gawron/.julia/packages/CuArrays/eFBar/src/broadcast.jl:48
  culiteral_pow(::typeof(^), !Matched::Union{Float32, Float64}, !Matched::Val{0}) at /home/gawron/.julia/packages/CuArrays/eFBar/src/broadcast.jl:44
  ...
```

**Expected behavior**
Uncommenting the lines in the example
```julia
using ForwardDiff
CuArrays.culiteral_pow(::typeof(^), x::ForwardDiff.Dual{Nothing,Float32,1}, ::Val{2}) = x*x
```
fixes the issue.

**Environment details**
Details on Julia:
```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7 CPU         950  @ 3.07GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, nehalem)
```

Julia packages:
 - `CUDAapi v1.0.1`
 - `CUDAdrv v3.0.1`
 - `CUDAnative v2.2.1`
 - `CuArrays v1.1.0`
 - `Flux v0.8.3`

CUDA: toolkit and driver version
`nvidia-smi` output:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:02:00.0  On |                  N/A |
| 30%   57C    P2    39W / 120W |   1102MiB /  6069MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

### PR DESCRIPTION
**Pull request by xukai92**

### CODE REVIEW

**Comment by appleparan** [comment]
It would be nice if there are some tests.

**Comment by xukai92** [comment]
Tests are there. Would be nice if someone can review this PR :) Thanks.

**Comment by benchislett** [comment]
Does this have to be restricted to real values? If so, I think this will still throw:
```julia
x = CuArrays.ones(Complex{Float64}, 1)
x .^ 2
# ERROR: MethodError: no method matching culiteral_pow(::typeof(^), ::Complex{Float64}, ::Val{2})
```
Otherwise, FWIW, the PR looks good

File: src/broadcast.jl [hunk 1]
```diff
@@ -41,11 +41,11 @@ for f in libdevice
...
-culiteral_pow(::typeof(^), x::Union{Float32, Float64}, ::Val{0}) = one(x)
-culiteral_pow(::typeof(^), x::Union{Float32, Float64}, ::Val{1}) = x
-culiteral_pow(::typeof(^), x::Union{Float32, Float64}, ::Val{2}) = x*x
-culiteral_pow(::typeof(^), x::Union{Float32, Float64}, ::Val{3}) = x*x*x
-culiteral_pow(::typeof(^), x::Union{Float32, Float64}, ::Val{p}) where p = CUDAnative.pow(x, Int32(p))
+culiteral_pow(::typeof(^), x::T, ::Val{0}) where {T<:Real} = one(x)
+culiteral_pow(::typeof(^), x::T, ::Val{1}) where {T<:Real} = x
+culiteral_pow(::typeof(^), x::T, ::Val{2}) where {T<:Real} = x * x
+culiteral_pow(::typeof(^), x::T, ::Val{3}) where {T<:Real} = x * x * x
+culiteral_pow(::typeof(^), x::T, ::Val{p}) where {T<:Real,p} = CUDAnative.pow(x, Int32(p))
```
Comment (benchislett) [inline src/broadcast.jl]: How does this add anything over the original implementation?
[CUDAnative.pow seems to only accept Float32/64 anyway](https://github.com/JuliaGPU/CUDAnative.jl/blob/9298b61a9b9ca5c84939eb6d59d0114bde7a1a27/src/device/cuda/math.jl#L191), how is this any different?

Comment (appleparan) [reply src/broadcast.jl]: This might help to understand.
https://github.com/JuliaDiff/ForwardDiff.jl/blob/958711d983a3f4a18521b846c4cec9219137eb0d/src/dual.jl#L469-L479

**Comment by vchuravy** [comment]
Please squash the commits into one

File: src/broadcast.jl (hunk 1 above)
Comment (benchislett) [reply src/broadcast.jl]: Won't the last call still break though?
The call to CUDAnative won't be found if `! T<:Union{Float32, Float64}`

**Comment by xukai92** [comment]
@vchuravy Done.

**Comment by vchuravy** [comment]
bors try

**Comment by xukai92** [comment]
Any idea what I should do to fix the build?

**Comment by xukai92** [comment]
I did a merge with master. Maybe this would fix the build.

**Comment by appleparan** [comment]
bors try

**Comment by appleparan** [comment]
Why log said "out of memory"? was it temporary issue?

**Comment by maleadt** [comment]
bors try

**Comment by appleparan** [comment]
Why `Flux` tests (rnn) fail (especially when `batch_size = 5`) ? is this due to #404 ?

**Comment by maleadt** [comment]
Why would it? RNN tests have been flaky for ages, I'm hoping that the refactor in https://github.com/JuliaGPU/CuArrays.jl/pull/404 might finally find out why (I haven't yet, even though there are some type issues with the current wrappers).
